### PR TITLE
readme: add header:

### PR DESCRIPTION
**Pull request by gucio321**
- discord link
- license badge
- twitch link

the readme should look better now ;-)

### CODE REVIEW

**Comment by DarthGandalf** [comment]
IRC link?

**Comment by cookta2012** [comment]
irc://irc.libera.chat/opendiablo2
If he wants to add it

**Comment by gucio321** [comment]
hmm, can't see any nice badge for it... or irc is on shields.io and I just don't see it?...

**Comment by DarthGandalf** [comment]
No idea about badge

This uses text:

https://github.com/AbyssEngine/AbyssEngine/blob/f00da3a2a61beebcbc7e5539813efe30fd9b2db9/README.md?plain=1#L8

**Comment by gucio321** [comment]
oke, added it

**Pull request merged**
